# This workflow uses actions provided by third parties and includes caching
# for optimal use in GitHub Actions to improve execution time.
# It builds a Java project using Gradle and submits dependency information for Dependabot Alerts.
# For more details, visit: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  # Triggers the workflow on push or pull request events to the 'main' branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Defines the environment to run the job
    runs-on: ubuntu-latest
    permissions:
      contents: read # Grants read-only access to repository content

    steps:
    # Step 1: Check out the code from the repository
    - uses: actions/checkout@v4

    # Step 2: Set up the Java Development Kit (JDK) version 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Make the Gradle Wrapper script executable to avoid permission issues
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    # Step 4: Set up Gradle and prepare caching for dependencies
    # This uses a specific version of the Gradle setup action
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    # Step 5: Build the project using the Gradle Wrapper
    - name: Build with Gradle Wrapper
      run: ./gradlew build

  dependency-submission:
    # Defines the environment to run the job
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grants write permissions to submit the dependency graph

    steps:
    # Step 1: Check out the code from the repository
    - uses: actions/checkout@v4

    # Step 2: Set up the Java Development Kit (JDK) version 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Make the Gradle Wrapper script executable to avoid permission issues
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    # Step 4: Generate and submit the dependency graph for Dependabot Alerts
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
